In [1]:
# Eigenvalue problems
# Libraries
import numpy as np
import math
import scipy.linalg as cpy
# import time
# import sys, os

In [2]:
# Parameters for testing
def initialize(n = 5, tol = 1e-10):
    Aux = np.zeros(n)
    Aux[0] = 2. 
    Aux[1] = -1.
    toe = cpy.toeplitz(Aux)
    print(toe)
    return(toe, n, tol)

# Search function (returns largest nondiag value and position in matrix)
def tracking(A,m):
    Mval = 0
    for ii in range(0,m):
        for jj in range(ii+1,m):
            if abs(A[ii,jj]) > abs(Mval):
                Mval = A[ii,jj]
                row = ii
                col = jj
    return(row, col, Mval)

def rotation(A, V, m, row, col):
    
    # Ang calculation
    tau = (A[col,col] - A[row,row]) / (2. * A[row,col])
    t = 1. / (abs(tau) + math.sqrt(tau**2 + 1.))
    if tau < 0:
        t = -t
    c = 1. / math.sqrt(1. + t**2)
    s = c * t
    
    # Allocation original values
    a_row = A[row,row]
    a_col = A[col,col]
    
    # Rotating eigenvalues
    A[row,row] = (a_row * c**2) + (a_col * s**2) - (2. * A[row,col] * s * c)
    A[col,col] = (a_row * s**2) + (a_col * c**2) + (2. * A[row,col] * s * c)
    A[col,row] = A[row,col] = 0.
    for ii in range(m):
        if ii != row and ii != col:
                a_row = A[ii,row]
                a_col = A[ii,col]
                A[ii,row] = A[row,ii] = a_row * c - a_col * s
                A[ii,col] = A[col,ii] = a_col * c + a_row * s
                
    # Calculating eigenvectors
    for ii in range(m):
        v_row = V[ii,row]
        v_col = V[ii,col]
        V[ii,row] = v_row * c - v_col * s
        V[ii,col] = v_col * c + v_row * s

    return(A,V)

def sorting(lam,V,m):
    for ii in range(m-1):
        index = ii
        val = lam[ii]
        for jj in range(ii+1,m):
            if lam[jj] < val:
                index = jj
                val = lam[jj]
        if index != ii:
            sortvalue(lam,ii,index)
            sortvector(V,ii,index)
    return(lam,V)

def sortvalue(vec,ii,jj):
    auxi = vec[ii]
    auxj = vec[jj]
    vec[ii] = auxj
    vec[jj] = auxi
    return(vec,ii,jj)

def sortvector(vec,ii,jj):
    vec[:,[ii,jj]] = vec[:,[jj,ii]]

In [3]:
# Load initial parameters
A, m, tol = initialize()
# A = np.array([[4.,2.,0.,0.], [2.,4.,1.,0], [0.,1.,3.,1], [0.,0.,1.,5.]])

[[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  2.]]


In [4]:
#row,col, mval = tracking(A,m)

In [5]:
#A = rotation(A,m,col,row)
#print(A)

In [6]:
V = np.identity(m,float)
mval = 1
ii = 0
while abs(mval) > tol:
    row,col,mval = tracking(A,m)
    A,V = rotation(A,V,m,col,row)
    ii += 1
    #print("Iteration: ", ii, "Max_val = ", mval)
    #print(A)
    #print("============================================")
lam = np.diag(A)
lam.setflags(write=1)
print("===================================================")
print(lam)

[0.58578644 3.41421356 2.        ]


In [7]:
lam,V=sorting(lam,V,m)
print(lam)

[0.58578644 2.         3.41421356]


In [8]:
for n in range(m):
    print(V[:,n])

[0.5        0.70710678 0.5       ]
[-7.07106781e-01  3.25218477e-16  7.07106781e-01]
[-0.5         0.70710678 -0.5       ]


In [9]:
print(V)

[[ 5.00000000e-01 -7.07106781e-01 -5.00000000e-01]
 [ 7.07106781e-01  3.25218477e-16  7.07106781e-01]
 [ 5.00000000e-01  7.07106781e-01 -5.00000000e-01]]
