In [1]:
import numpy as np
import math
cc = 0

In [2]:
Mval = 0
A  = 10*np.random.rand(5,5)
print(A)
mm = len(A)
np.max(A)

[[3.61064918 2.68799425 8.26255771 9.39045036 3.43621063]
 [4.03677843 2.61409755 8.852059   1.28256495 3.94580483]
 [6.81852816 2.21645344 0.56400933 8.77324372 4.43487023]
 [0.31252798 3.64755469 4.98784838 6.68082734 6.78658292]
 [6.33628619 9.40634533 9.40765845 9.29558002 8.57234801]]


9.407658450668041

In [3]:
for ii in range(0,5):
    # print(ii)
    for jj in range(0,mm):
        # print(jj)
        if ii != jj:
            if abs(A[ii,jj]) > abs(Mval):
                Mval = A[ii,jj]
                ll = ii
                kk = jj
                cc = cc+1
print(cc,Mval,"Position= (",ll,kk,")")
            

5 9.407658450668041 Position= ( 4 2 )
