In [1]:
# Libraries
import numpy as np
import scipy.linalg
from scipy.sparse import diags
import time
import sys, os
from math import sqrt

In [2]:
# Parameters
def inicial(sz = 4, tol = 1e-10):
    diags3 = np.array([-1 *np.ones(sz - 1),2 * np.ones(sz),-1 * np.ones(sz - 1)])
    config = [-1,0,1]
    A = diags(diags3,config).toarray()
    # A = np.array([[3.,1.,0.,0.], [1.,2.,3.,0], [0.,2.,2.,4], [0.,0.,5.,1.]])
    # A = np.array([[9.,5.,4.,3.],[9.,9.,2.,4.],[9.,9.,9.,8.],[9.,9.,9.,9.]])
    # A = 10*np.random.rand(5,5)
    print(A)
    return(A,sz,tol)

In [3]:
def j_rotation(M,R,l,k):
    a = 0
    

In [4]:
# Search Function
def search_m(M,dim):
    Mval = 0
    for ii in range(0,dim-1):
        for jj in range(ii+1,dim):
            if abs(M[ii,jj]) > abs(Mval):
                Mval = M[ii,jj]
                l = ii
                k = jj
    return(Mval,l,k)

In [5]:
A,m,tol = inicial()

[[ 2. -1.  0.  0.]
 [-1.  2. -1.  0.]
 [ 0. -1.  2. -1.]
 [ 0.  0. -1.  2.]]


In [10]:
Mval,ll,kk = search_m(A,m)

In [11]:
akl = A[kk,ll]
akk = A[kk,kk]
all_= A[ll,ll]
tau = (all_ - akk) / (2 * akl)
t = 1 / (abs(tau) + sqrt(1 + tau ** 2))
if tau < 0.0: t = -t
c = 1 / sqrt(1 + tau **2)
s = c * t
A[kk,ll] = 0; A[ll,kk] = 0;
A[ll,ll]=all_*c*c-2*akl*c*s+akk*s*s;
A[kk,kk]=all_*s*s+2*akl*c*s+akk*c*c;
print(A)

[[6. 0. 0. 0.]
 [0. 6. 0. 0.]
 [0. 0. 6. 0.]
 [0. 0. 0. 2.]]
